version: '3.2'
services:
  test-socket-redis:
    build:
      context: .
      dockerfile: Dockerfile-test
      args:
        FROM_TAG: latest
    image: socket-redis-test:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SOCKET_PORTS=8090
      - STATUS_PORT=8085
      - STATUS_TOKEN=
    depends_on:
      - redis

  redis:
    image: redis:3.2.6
    command: '/redis/config/redis.conf'
    volumes:
      - ./docker/config/redis/redis.conf:/redis/config/redis.conf
